-- MySQL Script generated by MySQL Workbench
-- Tue Nov 11 20:28:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ReservasCompañiaTransporte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ReservasCompañiaTransporte` ;

-- -----------------------------------------------------
-- Schema ReservasCompañiaTransporte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ReservasCompañiaTransporte` DEFAULT CHARACTER SET utf8 ;
USE `ReservasCompañiaTransporte` ;

-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Viajes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Viajes` (
  `id_viaje` INT NOT NULL AUTO_INCREMENT,
  `origen` VARCHAR(80) NOT NULL,
  `destino` VARCHAR(80) NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `fecha_llegada` DATE NULL,
  `precio_boleto` DOUBLE NOT NULL,
  PRIMARY KEY (`id_viaje`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Pasajeros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Pasajeros` (
  `id_pasajeros` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apeliido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `correo_electronico` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_pasajeros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Asientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Asientos` (
  `id_asientos` INT NOT NULL,
  `nro_asiento` INT NULL,
  `disponibilidad` TINYINT(1) NULL,
  PRIMARY KEY (`id_asientos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Reservas` (
  `id_reserva` INT NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NULL,
  `Viajes_id_viaje` INT NOT NULL,
  `Pasajeros_id_pasajeros` INT NOT NULL,
  `Asientos_id_asientos` INT NOT NULL,
  PRIMARY KEY (`id_reserva`, `Viajes_id_viaje`, `Pasajeros_id_pasajeros`, `Asientos_id_asientos`),
  INDEX `fk_Reservas_Viajes_idx` (`Viajes_id_viaje` ASC) VISIBLE,
  INDEX `fk_Reservas_Pasajeros1_idx` (`Pasajeros_id_pasajeros` ASC) VISIBLE,
  INDEX `fk_Reservas_Asientos1_idx` (`Asientos_id_asientos` ASC) VISIBLE,
  CONSTRAINT `fk_Reservas_Viajes`
    FOREIGN KEY (`Viajes_id_viaje`)
    REFERENCES `ReservasCompañiaTransporte`.`Viajes` (`id_viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Pasajeros1`
    FOREIGN KEY (`Pasajeros_id_pasajeros`)
    REFERENCES `ReservasCompañiaTransporte`.`Pasajeros` (`id_pasajeros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Asientos1`
    FOREIGN KEY (`Asientos_id_asientos`)
    REFERENCES `ReservasCompañiaTransporte`.`Asientos` (`id_asientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Vehiculo` (
  `idVehiculo` INT NOT NULL,
  `nro_placa` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `capacidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVehiculo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ReservasCompañiaTransporte`.`Conductores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ReservasCompañiaTransporte`.`Conductores` (
  `id_conductores` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `nro_licencia` BIGINT NOT NULL,
  `Vehiculo_idVehiculo` INT NOT NULL,
  PRIMARY KEY (`id_conductores`, `Vehiculo_idVehiculo`),
  INDEX `fk_Conductores_Vehiculo1_idx` (`Vehiculo_idVehiculo` ASC) VISIBLE,
  CONSTRAINT `fk_Conductores_Vehiculo1`
    FOREIGN KEY (`Vehiculo_idVehiculo`)
    REFERENCES `ReservasCompañiaTransporte`.`Vehiculo` (`idVehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
